query GetVehicle($input: GetVehicleInput!) {
    getVehicle(input: $input) {
        __typename
        ... on VehicleNotFound {
            __typename
            message
        }
        ... on PermissionDenied {
            __typename
            message
        }
        ... on InventoriedVehicle {
            __typename
            vehicleId
            addedAt
            updatedAt
            status
            vehicle {
                make
                model
                year
            }
            avatar
            images
        }
    }
}
