query ListVehicles($input:ListVehiclesInput!) {
    listVehicles(input:$input) {
        vehicles {
            vehicleId
            make
            model
            year
        }
        totalCount
        nextPageToken
        prevPageToken
    }
}
