apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "base-service.fullname" . }}
  namespace: {{ quote .Release.Namespace }}
  labels:
{{ include "base-service.labels" . | indent 4 }}  
data:
  SECRETS_DIR: {{ .Values.secretsDir }}
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}