apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-service.fullname" . }}
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "base-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "base-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "base-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{ if has ["grpc", "http"] .Values.backendType }}
          ports:
          {{ if eq .Values.backendType "http" }}
            - name: http
              containerPort: 80
              protocol: TCP
          {{ else if eq .Values.backendType "grpc" }} 
            - name: grpc
              containerPort: 50051
              protocol: TCP
          {{ else }}
            {{ fail "Invalid backend type"}}
          {{ end }}
          {{ end }}
          livenessProbe:
          {{ if eq .Values.backendType "grpc" }}
            # ref: https://github.com/grpc-ecosystem/grpc-health-probe 
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
              initialDelaySeconds: 10
          {{ else if eq .Values.backendType "http" }}
            httpGet:
              path: /_health
              port: http
          {{ else if eq. Values.backendType "console" }}
            exec:
              command: ["stat", "/tmp/.lock"]
              initialDelaySeconds: 10
          {{ else }}
            {{ fail "Invalid backend type" }}
          {{ end }}
          {{ if has ["grpc", "http"] .Values.backendType }}
          readinessProbe:
          {{ if eq .Values.backendType "grpc" }}
            # ref: https://github.com/grpc-ecosystem/grpc-health-probe 
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50051"]
              initialDelaySeconds: 5
          {{ else if eq .Values.backendType "http" }}
            httpGet:
              path: /_health
              port: http
          {{ else }}
            {{ fail "Invalid backend type" }}
          {{ end }}
          {{ end }}
          envFrom:
            - configMapRef:
                name: {{ include "base-service.fullname" . }}
          volumeMounts:
          {{- $secretsDir := .Values.secretsDir -}}
          {{- range .Values.secrets }}
            - name: {{ . }}-volume
              readOnly: true
              mountPath: {{ $secretsDir }}/{{ . }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- range .Values.secrets }}
        - name: {{ . }}-volume
          secret:
            secretName: {{ . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
