kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "base-service.fullname" . }}-read-rolebinding
  namespace: {{ quote .Release.Namespace }}
  labels:
{{ include "base-service.labels" . | indent 4 }}  
subjects:
  - kind: ServiceAccount
    name: {{ template "base-service.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "base-service.name" . }}-read
