kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "base-service.fullname" . }}-read
  namespace: {{ quote .Release.Namespace }}
  labels:
{{ include "base-service.labels" . | indent 4 }}  
rules:
  - apiGroups: [""]
    resources: ["secrets","configmaps"]
    verbs: ["get", "list", "watch"]
