{{ if has ["grpc", "http"] .Values.backendType }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-service.fullname" . }}
  labels:
    {{- include "base-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{ if eq .Values.backendType "grpc" }}
    - name: grpc
      port: {{ .Values.servicePort }}
      targetPort: grpc
      protocol: TCP
  {{ else if eq .Values.backendType "http" }}
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: http
      protocol: TCP
  {{ else }}
    {{ fail "Invalid backend type" }}
  {{ end }}
  selector:
    {{- include "base-service.selectorLabels" . | nindent 4 }}
{{ end }}