version: '1.0'
stages:
  - test
steps:
  test_api:
    stage: test
    type: composition
    title: Test Lease API
    composition:
      version: '3'
      services:
        eventstore:
          image: eventstore/eventstore
    composition_candidates:
      test:
        build:
          context: .
          target: test-runtime
        environment:
          - EVENTSTORE_PROTOCOL=tcp
          - EVENTSTORE_HOST=eventstore
          - EVENTSTORE_PORT=1113
          - EVENTSTORE_USER=admin
          - EVENTSTORE_PASSWORD=changeit
