version: '1.0'
stages:
  - test
steps:
  build_api:
    stage: build
    type: build
    title: Build Lease API
    image_name: lease-api
    target: test-runtime
  test_api:
    stage: test
    type: composition
    title: Test Lease API
    composition:
      version: '3'
      services:
        eventstore:
          image: eventstore/eventstore
    composition_candidates:
      test:
        image: ${{build_api}}
        environment:
          - EVENTSTORE_PROTOCOL=tcp
          - EVENTSTORE_HOST=eventstore
          - EVENTSTORE_PORT=1113
          - EVENTSTORE_USER=admin
          - EVENTSTORE_PASSWORD=changeit
