version: '1.0'
stages:
  - build
  - test
steps:
  build_test_proto_image:
    stage: build
    type: build
    title: Build test image
    working_directory: proto/.devcontainer
    dockerfile: Dockerfile
    image_name: equinox-tutorial/test-proto
    build_arguments:
      - NUGET_PACKAGES=/codefresh/volume/.nuget/packages
  test_protos:
    stage: test
    title: Test protos
    image: ${{build_test_proto_image}}
    working_directory: proto
    commands:
      - rm -rf paket-files
      - fake build -t Test
  build_lease_api:
    stage: build
    type: build
    title: Build Lease API
    image_name: lease-api
    target: tester
  test_lease_api:
    stage: test
    type: composition
    title: Test Lease API
    composition:
      version: '3'
      services:
        eventstore:
          image: eventstore/eventstore
    composition_candidates:
      test:
        image: ${{build_lease_api}}
        command: bash -c "./wait-for.sh http://eventstore:2113/users/admin && dotnet Tests.dll"
        environment:
          - EVENTSTORE_PROTOCOL=tcp
          - EVENTSTORE_HOST=eventstore
          - EVENTSTORE_PORT=1113
          - EVENTSTORE_USER=admin
          - EVENTSTORE_PASSWORD=changeit
