version: '3.4'
services:
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      EVENTSTORE_START_STANDARD_PROJECTIONS: "True"
      EVENTSTORE_RUN_PROJECTIONS: All
  seq:
    image: datalust/seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "8081:80"
      - "5341:5341"
  lease-api:
    build:
      context: ./lease-api
      target: runner
    ports:
      - "50051:50051"
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 50051
      EVENTSTORE_PROTOCOL: tcp
      EVENTSTORE_HOST: eventstore
      EVENTSTORE_TCP_PORT: 1113
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_USER: admin
      EVENTSTORE_PASSWORD: changeit
      SEQ_HOST: seq
      SEQ_PORT: 5341
    depends_on:
      - seq
      - eventstore
  graphql-api:
    build:
      context: ./graphql-api
      target: runner
    ports:
      - "4000:4000"
    environment:
      SERVER_HOST: '0.0.0.0'
      SERVER_PORT: 4000
      LEASE_API_HOST: lease-api
      LEASE_API_PORT: 50051
      SEQ_HOST: logs
      SEQ_PORT: 5341
    depends_on:
      - lease-api
  web-app:
    build:
      context: ./web-app
    volumes:
      - ./web-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - graphql-api
