version: '3'
services:
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
  api:
    build:
      context: .
    environment:
      - EVENTSTORE_PROTOCOL=tcp
      - EVENTSTORE_HOST=eventstore
      - EVENTSTORE_PORT=1113
      - EVENTSTORE_USER=admin
      - EVENTSTORE_PASSWORD=changeit
    ports:
      - "8080:8080"
