version: '3.4'
services:
  eventstore:
    image: eventstore/eventstore
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      EVENTSTORE_START_STANDARD_PROJECTIONS: "True"
      EVENTSTORE_RUN_PROJECTIONS: All
  logs:
    image: datalust/seq
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "8081:80"
      - "5341:5341"
  lease-api:
    build:
      context: ./lease-api
      target: runner
    environment:
      DEBUG: "true"
      PORT: 50051
      EVENTSTORE_PROTOCOL: tcp
      EVENTSTORE_HOST: eventstore
      EVENTSTORE_TCP_PORT: 1113
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_USER: admin
      EVENTSTORE_PASSWORD: changeit
      SEQ_HOST: logs
      SEQ_PORT: 5341
    ports:
      - "50051:50051"
    depends_on:
      - logs
      - eventstore
  graphql-api:
    build:
      context: ./graphql-api
      target: runner
    environment:
      DEBUG: "true"
      PORT: 4000
      LEASE_API_HOST: lease-api
      LEASE_API_PORT: 50051
      SEQ_HOST: logs
      SEQ_PORT: 5341
    ports:
      - "4000:4000"
    depends_on:
      - lease-api
