version: '3.4'
services:
  seq:
    image: datalust/seq:5.1
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "8081:80"
  minio:
    image: minio/minio
    command: ["server", "/data"]
    environment: 
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ports: 
      - "9000:9000"
  eventstore:
    image: eventstore/eventstore:release-5.0.8
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      EVENTSTORE_START_STANDARD_PROJECTIONS: "True"
      EVENTSTORE_RUN_PROJECTIONS: All
  mongo:
    image: mongo:4.2
    command: ["mongod", "--replSet", "rs0"]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeit
    ports: 
      - "27017:27017"
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
  upload-api:
    build: ./client/upload-api
    ports: 
      - "8082:8080"
    environment: 
      SECRET_DIR: /var/secrets
      SERVER_PORT: 8080
      SEQ_SCHEME: http
      SEQ_HOST: seq
      S3_SCHEME: http
      S3_HOST: minio
      S3_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      S3_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
      S3_UPLOAD_BUCKET: upload
    depends_on: 
      - seq
      - minio
  vehicle-processor:
    build:
      context: ./vehicle
      dockerfile: deploy/processor.Dockerfile
      target: runner
    ports:
      - "50051:50051"
    environment:
      DEBUG: "true"
      SERVER_PORT: 50051
      EVENTSTORE_HOST: eventstore
      SEQ_HOST: seq
    depends_on:
      - seq
      - eventstore
  vehicle-reactor:
    build:
      context: ./vehicle
      dockerfile: deploy/reactor.Dockerfile
      target: runner
    environment: 
      DEBUG: "true"
      EVENTSTORE_HOST: eventstore
      MONGO_HOST: mongo
      MONGO_REPLICA_SET: rs0
      SEQ_HOST: seq
    depends_on: 
      - seq
      - eventstore
      - mongo
      - vehicle-processor
  vehicle-reader:
    build:
      context: ./vehicle
      dockerfile: deploy/reader.Dockerfile
      target: runner
    ports:
      - "50052:50052"
    environment: 
      DEBUG: "true"
      SERVER_PORT: 50052
      MONGO_HOST: mongo
      MONGO_REPLICA_SET: rs0
      SEQ_HOST: seq
    depends_on: 
      - seq
      - eventstore
      - mongo
      - vehicle-processor
      - vehicle-reactor
  graphql-api:
    build:
      context: ./client/graphql-api
      target: runner
    ports:
      - "4000:4000"
    environment:
      DEBUG: "true"
      SERVER_PORT: 4000
      VEHICLE_PROCESSOR_HOST: vehicle-processor
      VEHICLE_PROCESSOR_PORT: 50051
      VEHICLE_READER_HOST: vehicle-reader
      VEHICLE_READER_PORT: 50052
      SEQ_HOST: seq
    depends_on: 
      - vehicle-processor
      - vehicle-reader
  web-app:
    build:
      context: ./client/web-app
    environment:
      GRAPHQL_API_HOST: localhost
      GRAPHQL_API_PORT: 4000
    volumes:
      - ./fable-web-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - graphql-api
