version: '3.4'
services:
  eventstore:
    image: eventstore/eventstore:release-5.0.8
    ports:
      - "2113:2113"
      - "1113:1113"
    environment:
      EVENTSTORE_START_STANDARD_PROJECTIONS: "True"
      EVENTSTORE_RUN_PROJECTIONS: All
  seq:
    image: datalust/seq:5.1
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - "8081:80"
      - "5341:5341"
  vehicle-api:
    build:
      context: ./vehicle-api
      target: runner
    ports:
      - "50051:50051"
    environment:
      SERVER_PORT: 50051
      EVENTSTORE_HOST: eventstore
      SEQ_HOST: seq
    depends_on:
      - seq
      - eventstore
  graphql-api:
    build:
      context: ./graphql-api
      target: runner
    ports:
      - "4000:4000"
    environment:
      SERVER_PORT: 4000
      LEASE_API_HOST: lease-api
      LEASE_API_PORT: 50051
      SEQ_HOST: seq
      SEQ_PORT: 5341
  test-graphql-api:
    build:
      context: ./graphql-api
      target: tester
    environment:
      GRAPHQL_API_HOST: graphql-api
      GRAPHQL_API_PORT: 4000
    depends_on:
      - graphql-api
  web-app:
    build:
      context: ./web-app
    environment:
      REACT_APP_GRAPHQL_HOST: localhost
      REACT_APP_GRAPHQL_PORT: 4000
    volumes:
      - ./web-app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "35729:35729"
    depends_on:
      - graphql-api
