config:
  auth0:clientId:
    secure: AAABAFR+rvh7kGFtPZLHBzg4wxYP+yb53LopY/oOVIvEahBt2vQnVzxze4mU7k+X3p6oGb7hrwwftHkTEZz1nA==
  auth0:clientSecret:
    secure: AAABAHyxcyXs+M1D634v3Vh9KL/wFd2+UC8A1qmoYZOmon202djqxQFfEEi9QUQtuFEAtIrfP1JklHaZuRjiRllofFdX9yrGmXkNmaPG+m8kcZ8HX+XYver0QT7E5fzf
  auth0:domain: ameier38.auth0.com
  cloudflare:apiKey:
    secure: AAABAGcLK47IXbyhatJM1pUEmC6yXHVKSHcWLK2gGXaHAfHp+U9iVE5Kv07wtPpRu/A0t92XHQBFU79UV+nob+yCDX83j9El
  cloudflare:email:
    secure: AAABACKkoA/SmrlDkdSkqO9OoJobsMI5esCFggUd1z7OtHmj0abYmDBY0VgIgoRC1xA=
  digitalocean:spacesAccessId:
    secure: AAABAN5JlYrC/bXAbUuwtcbOc8y3oZSlB0B1XgqOVGBdRbw1X8HyzhU3o6r1RLvzZ0uXMg==
  digitalocean:spacesSecretKey:
    secure: AAABAA3B+RkVv4Dt7xqWOYlmhBUW5Ryyucq5FFWwU5fEDiOh2LklFJ2bqDlFAlMY2AdB23rupZ6nnugWB1FBjlThi+m84I1ofaSw
  digitalocean:token:
    secure: AAABAFVQb/qpaR3owg+pyzpjJWzmdfDdb/QNud2BgagR6yOnEjklPzUkueiAoaJAUPiHwv+mO1egeZIHlb3SFrpsm7M0S4GYuRx+zp+PRp6t88q3w/mhBYUpo7Eeqmwg
  dns:zone: cosmicdealership.com
  eventstore:adminPassword:
    secure: AAABAJNc3zw+wgHyN6qT6YbDx7i6qS655z9c5i8eib4NKrepR1jtBg==
  eventstore:vehicleProcessorPassword:
    secure: AAABAMr7m3kSDW56yh7l+M5br/zz4qmuRCCQSjPfkTRvM5cG7yOXUA==
  eventstore:vehicleReactorPassword:
    secure: AAABAKvVaDUC3wtPZ/SaK1dQneOhDg8Qnu3jngg/rzQu/d10wKoKeg==
  mongo:adminPassword:
    secure: AAABAMEjFHcG40RuQdnxKbKjUSZGINtgRIFqjEWxYEN2FT08xZOTMQ==
  mongo:adminUser: admin
  mongo:vehicleReactorPassword:
    secure: AAABABG9p7pL7o7jULhQrCozz8IZKlBoEwsvoiqhK824WQMIRjLC9A==
  mongo:vehicleReaderPassword:
    secure: AAABAGv+TUDNvNz6rftEMlvG3d5Lde6gskHnbhPcnoe07R9RmvulZA==
