mutation RemoveVehicle($input:RemoveVehicleInput!) {
    removeVehicle(input: $input) {
        __typename
        ...on Success {
            __typename
            message
        }
        ... on VehicleNotFound {
            __typename
            message
        }
        ... on PermissionDenied {
            __typename
            message
        }
    }
}
