site_name: Cosmic Dealership
dev_addr: '0.0.0.0:8000'
theme:
  name: material
  palette:
    primary: purple
  logo: assets/images/rocket.svg
  favicon: assets/images/rocket.svg
plugins:
  - search
  - awesome-pages:
      collapse_single_pages: true
markdown_extensions:
  - admonition
  - pymdownx.superfences
