mutation AddVehicleImage($input:AddVehicleImageInput!) {
    addVehicleImage(input: $input) {
        __typename
        ...on Success {
            __typename
            message
        }
        ... on NotFound {
            __typename
            message
        }
        ... on PermissionDenied {
            __typename
            message
        }
    }
}
