query ListVehicles($input:ListVehiclesInput!) {
    listVehicles(input:$input) {
        __typename
        ... on PageTokenInvalid {
            __typename
            message
        }
        ... on PageSizeInvalid {
            __typename
            message
        }
        ... on PermissionDenied {
            __typename
            message
        }
        ... on ListVehiclesSuccess {
            __typename
            totalCount
            nextPageToken
            vehicles {
                vehicleId
                avatar
                addedAt
                status
                vehicle {
                    make
                    model
                    year
                }
            }
        }
    }
}
