query GetAvailableVehicle($input: GetVehicleInput!) {
    getAvailableVehicle(input: $input) {
        __typename
        ... on VehicleNotFound {
            __typename
            message
        }
        ... on InventoriedVehicle {
            __typename
            vehicleId
            status
            vehicle {
                make
                model
                year
            }
        }
    }
}
