query GetAvailableVehicle($input:GetVehicleInput!) {
    getAvailableVehicle(input:$input) {
        __typename
        ... on VehicleNotFound {
            __typename
            message
        }
        ... on InventoriedVehicle {
            __typename
            vehicleId
            addedAt
            updatedAt
            vehicle {
                make
                model
                year
            }
            status
            avatar
            images
        }
    }
}
