query ListAvailableVehicles($input:ListVehiclesInput!) {
  listAvailableVehicles(input: $input) {
    vehicles {
      vehicleId
      make
      model
      status
    }
    nextPageToken
    prevPageToken
    totalCount
  }
}
