name: Tutorial Pull Request
on: [pull_request]

jobs:
  generate_protos:
    # ref: https://github.com/actions/virtual-environments/issues/2
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Lint protos
        uses: ./.github/actions/prototool
        with:
          # `root` will get translated into `INPUT_ROOT` env var
          root: protos
          args: lint
      - name: Compile protos
        uses: ./.github/actions/prototool
        with:
          root: protos
          args: compile
      - uses: ./.github/actions/prototool
        with:
          root: protos
          args: generate
      - run: sudo chmod -R 777 protos/gen
      - uses: actions/upload-artifact@v1
        with:
          name: protos
          path: protos/gen
  test_lease_api:
    runs-on: ubuntu-16.04
    needs: [generate_protos]
    steps:
      - uses: actions/checkout@v1
      - name: Download protos to Lease API
        uses: actions/download-artifact@v1
        with:
          name: protos
          path: lease-api/src/Proto/gen
      - name: Start Lease API
        run: docker-compose up -d --build lease-api
      - name: Test Lease API
        uses: ./.github/actions/fake
        with:
          root: lease-api
          target: Test
  test_graphql_api:
    runs-on: ubuntu-16.04
    needs: [generate_protos,test_lease_api]
    steps:
      - uses: actions/checkout@v1
      - name: Download protos to Lease API
        uses: actions/download-artifact@v1
        with:
          name: protos
          path: lease-api/src/Proto/gen
      - name: Download protos to GraphQL API
        uses: actions/download-artifact@v1
        with:
          name: protos
          path: graphql-api/src/Proto/gen
      - name: Start GraphQL API
        run: docker-compose up -d --build graphql-api
      - name: Test GraphQL API
        uses: ./.github/actions/fake
        with:
          root: graphql-api
          target: Test
