name: Tutorial Pull Request
on: [pull_request]

jobs:
  generate_protos:
    # ref: https://github.com/actions/virtual-environments/issues/2
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Lint protos
        uses: ./.github/actions/prototool
        with:
          # `root` will get translated into `INPUT_ROOT` env var
          root: protos
          args: lint
      - name: Compile protos
        uses: ./.github/actions/prototool
        with:
          root: protos
          args: compile
      - uses: ./.github/actions/prototool
        with:
          root: protos
          args: generate
  test_lease_api:
    runs-on: ubuntu-16.04
    needs: [generate_protos]
    steps:
      - uses: actions/checkout@v1
      - name: Start Lease API
        run: docker-compose up -d --build lease-api
      - name: Test Lease API
        run: docker-compose run --rm test-lease-api
  test_graphql_api:
    runs-on: ubuntu-16.04
    needs: [generate_protos,test_lease_api]
    steps:
      - uses: actions/checkout@v1
      - name: Start Lease API and GraphQL API
        run: docker-compose up -d --build graphql-api
      - name: Test GraphQL API
        run: docker-compose run --rm test-graphql-api
