name: Pull Request
on: [pull_request]

jobs:
  generate_protos:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate protos
        run: docker-compose run --rm generate-protos
      - name: Upload generated protos
        uses: actions/upload-artifact@v2
        with:
          name: protos
          path: ./protos/gen
          retention-days: 1
  test:
    runs-on: ubuntu-18.04
    needs: [generate_protos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download protos
        uses: actions/download-artifact@v2
        with:
          name: protos
          path: ./protos/gen
      - name: Update Vehicle Protos
        run: ./.github/actions/fsharp
        with:
          root: vehicle
          target: UpdateProtos
      - name: Update GraphQL Protos
        uses: ./.github/actions/fsharp
        with:
          root: graphql
          target: UpdateProtos
      - name: Build Services
        run: docker-compose up -d --build
      - name: Test Vehicle Integrations
        run: docker-compose run --rm test-vehicle
      - name: Test GraphQL Integrations
        run: docker-compose run --rm test-graphql
      - name: Test Web Integrations
        run: docker-compose run --rm test-web
